### ISSUE TITLE
Add husky and lint-staged pre-commit hook

### ISSUE THREAD

**Issue by ashu8912** [vtechguys/alumniportalfrontend#2]
right now all the commits are not verified on the go sometime people make a pr and than realise that there are some problems with it,
a pre-commit hook will help us linting our code before we make a commit other benefits include running all test before commit(although tests are not yet added but in future they will be added)
running eslint before commit.
people who want to learn more about this hook
here is a link that might help
https://codeburst.io/continuous-integration-lint-staged-husky-pre-commit-hook-test-setup-47f8172924fc

**Comment by vtechguys** [comment]
This has been resolved. Refer this commit https://github.com/vtechguys/alumniportalfrontend/commit/8dbba324ba39b5b3da3235fd55c4ea15f0263870
