### ISSUE TITLE
hide password

### ISSUE THREAD

**Issue by ashu8912** [vtechguys/alumniportalfrontend#6]
<img width="1344" alt="Screenshot 2020-02-27 at 1 35 21 AM" src="https://user-images.githubusercontent.com/30126128/75385835-8f797900-5906-11ea-8a39-4dd04be5cd40.png">

**Comment by avnishsingh516** [comment]
#19

**Comment by vtechguys** [comment]
Resolved in https://github.com/vtechguys/alumniportalfrontend/pull/19. Merged to the `dev` branch.
